version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rocko
      MONGO_INITDB_ROOT_PASSWORD: delson
    volumes:
      - ./data:/data/db
